# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network :private_network, ip: "192.168.10.10"
    config.vm.box_check_update = true
    config.vm.hostname = "sntrsand"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "sntrsand"
        vb.memory = "2048"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/main.yml"
    end
end
